---
- hosts: all
  become: yes
  tasks:
  - name: unarchive
    unarchive:
            src: http://mirror.cc.columbia.edu/pub/software/apache/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.tar.gz 
      dest: /opt/tomcat
      remote_src: yes
      extra_opts:
      - --strip-components=1
